name: final_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: 3.4.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: 3.0.1
  just_audio: ^0.9.28
  path_provider: 2.0.11
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

fonts:
  - family: Mequran
    fonts:
      - asset: assets/fonts/mequran.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_quran.png"
